
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author denis
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_user = new javax.swing.JLabel();
        idnumf = new javax.swing.JTextField();
        lbl_pass = new javax.swing.JLabel();
        passwordf = new javax.swing.JPasswordField();
        signupb = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_name = new javax.swing.JLabel();
        namef = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(133, 156, 191));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(72, 99, 142));
        jLabel3.setText("VOTING SYSTEM");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/votebox.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(72, 99, 142));

        lbl_user.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(51, 51, 51));
        lbl_user.setText("ID NUMBER");

        idnumf.setBackground(new java.awt.Color(72, 99, 142));
        idnumf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        idnumf.setForeground(new java.awt.Color(255, 255, 255));
        idnumf.setBorder(null);
        idnumf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idnumfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idnumfFocusLost(evt);
            }
        });
        idnumf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnumfActionPerformed(evt);
            }
        });

        lbl_pass.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_pass.setForeground(new java.awt.Color(51, 51, 51));
        lbl_pass.setText("PASSWORD");

        passwordf.setBackground(new java.awt.Color(72, 99, 142));
        passwordf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passwordf.setForeground(new java.awt.Color(255, 255, 255));
        passwordf.setBorder(null);
        passwordf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordfFocusLost(evt);
            }
        });
        passwordf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfActionPerformed(evt);
            }
        });

        signupb.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        signupb.setForeground(new java.awt.Color(133, 156, 191));
        signupb.setText("SIGN UP");
        signupb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbActionPerformed(evt);
            }
        });

        lbl_name.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setText("FULLNAME");

        namef.setBackground(new java.awt.Color(72, 99, 142));
        namef.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        namef.setForeground(new java.awt.Color(255, 255, 255));
        namef.setBorder(null);
        namef.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namefFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                namefFocusLost(evt);
            }
        });
        namef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefActionPerformed(evt);
            }
        });

        btn_back.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(133, 156, 191));
        btn_back.setText("BACK");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_name)
                        .addComponent(namef)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_pass)
                        .addComponent(lbl_user)
                        .addComponent(idnumf, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                        .addComponent(jSeparator1)
                        .addComponent(passwordf)
                        .addComponent(jSeparator2)))
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(signupb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namef, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_user, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idnumf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lbl_pass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(signupb)
                .addGap(18, 18, 18)
                .addComponent(btn_back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(95, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(175, 175, 175))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idnumfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnumfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idnumfActionPerformed

    private void passwordfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfActionPerformed

    private void passwordfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfFocusGained
        lbl_pass.setForeground(new Color(240,240,240));
        jSeparator2.setBackground(new Color(149,165,166));
    }//GEN-LAST:event_passwordfFocusGained

    private void passwordfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfFocusLost
        lbl_pass.setForeground(new Color(33,33,33));
        jSeparator2.setBackground(new Color(33,33,33));
    }//GEN-LAST:event_passwordfFocusLost

    private void idnumfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idnumfFocusGained
        lbl_user.setForeground(new Color(240,240,240));
        jSeparator1.setBackground(new Color(149,165,166));
    }//GEN-LAST:event_idnumfFocusGained

    private void idnumfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idnumfFocusLost
        lbl_user.setForeground(new Color(33,33,33));
        jSeparator1.setBackground(new Color(33,33,33));
    }//GEN-LAST:event_idnumfFocusLost

    private void namefFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namefFocusGained
        lbl_name.setForeground(new Color(240,240,240));
        jSeparator3.setBackground(new Color(149,165,166));
    }//GEN-LAST:event_namefFocusGained

    private void namefFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namefFocusLost
        lbl_name.setForeground(new Color(33,33,33));
        jSeparator3.setBackground(new Color(33,33,33));
    }//GEN-LAST:event_namefFocusLost

    private void namefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefActionPerformed

     public Connection getConnection(){
        String url = "jdbc:mysql://localhost:3306/voting_db?useTimezone=true&serverTimezone=UTC";
        String username = "root";
        String password = "";
        Connection con = null;

        try {
            con = DriverManager.getConnection(url,username,password);
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Not Connected.","Connection Error",JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
     /*public boolean checkUsername(String username)
     {
         PreparedStatement ps;
         ResultSet rs;
         boolean checkUser = false;
         String query ="SELECT *FROM `accounts_table` WHERE `username`=?";
         
         try{
              Connection con = getConnection();
              ps = con.prepareStatement(query);
              
              rs = ps.executeQuery();
              
              if(rs.next()){
                  checkUser = true;
              }
         }catch (SQLException ex){
             Logger.getLogger(SignUp.class.getName()).log(Level,SEVERE,null,ex);
         }
         return checkUser;
     }*/
 
    private void signupbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbActionPerformed
        
        String name = namef.getText();
        String idnumber = idnumf.getText();
        String username = namef.getText();
        String password = String.valueOf(passwordf.getPassword());
        
        if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Add Name");
        }
        
        else if(password.equals("")){
            JOptionPane.showMessageDialog(null,"Add Password");
        }
        
        PreparedStatement ps;
        String query = "INSERT INTO `accounts_table`(`name`,`idnumber`,`username`,`password`) VALUES (?,?,?,?)";
        
        try{
            Connection con = getConnection();
            ps = con.prepareStatement(query);
            
            ps.setString(1, name);
            ps.setString(2, idnumber);
            ps.setString(3, username);
            ps.setString(4, password);
            
            if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null, "Add");
            }
        }catch(SQLException ex){
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
}
        /*if (namef.getText() != null || idnumf.getText() != null || passwordf.getText() != null )
        {
            try {
                Connection con = getConnection();
                PreparedStatement ps = con.prepareStatement("INSERT INTO accounts_table(name,username,password)"
                        + "values(?,?,?,?,?) ");
                ps.setString(1, namef.getText());
                ps.setString(2, idnumf.getText());
                ps.setString(3, passwordf.getText());*/
            /*JOptionPane.showMessageDialog(null,"Incomplete Info.");*/
             /*JOptionPane.showMessageDialog(null, "Added!");
             dispose();
            new Login().setVisible(true);
            } catch (Exception ex) {
                 JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "hallo");*/
        
        /*else 
        {
           JOptionPane.showMessageDialog(null,"Sign up success!");
           namef.setText(null);
           idnumf.setText(null);
           passwordf.setText(null);
           dispose();
           new Login().setVisible(true);
        }*/
        
    }//GEN-LAST:event_signupbActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JTextField idnumf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_pass;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JTextField namef;
    private javax.swing.JPasswordField passwordf;
    private javax.swing.JButton signupb;
    // End of variables declaration//GEN-END:variables
}
